# Copyright 2024 The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


"""
Records a dataset.
Actions for the robot can be either generated by teleoperation or by a policy.
"""

import logging
import select
import sys
import time
import os
from threading import Lock
from concurrent.futures import ThreadPoolExecutor
from dataclasses import asdict, dataclass, field
from pathlib import Path
from pprint import pformat
from typing import Any, Optional
from typing import Any
from collections import deque
from pynput import keyboard

from dual_arm.cameras import (  # noqa: F401
    CameraConfig,  # noqa: F401
)
from dual_arm.cameras.opencv.configuration_opencv import OpenCVCameraConfig  # noqa: F401
from dual_arm.cameras.reachy2_camera.configuration_reachy2_camera import Reachy2CameraConfig  # noqa: F401
from dual_arm.cameras.realsense.configuration_realsense import RealSenseCameraConfig  # noqa: F401
from dual_arm.cameras.zmq.configuration_zmq import ZMQCameraConfig  # noqa: F401
from dual_arm.configs import parser
from dual_arm.configs.policies import PreTrainedConfig
from dual_arm.datasets.image_writer import safe_stop_image_writer
from dual_arm.datasets.lerobot_dataset import LeRobotDataset
from dual_arm.datasets.pipeline_features import (
    aggregate_pipeline_dataset_features,
    create_initial_features,
)
from dual_arm.datasets.utils import build_dataset_frame, combine_feature_dicts
from dual_arm.datasets.video_utils import VideoEncodingManager
from dual_arm.policies.factory import make_policy, make_pre_post_processors
from dual_arm.policies.pretrained import PreTrainedPolicy
from dual_arm.policies.utils import make_robot_action
from dual_arm.processor import (
    PolicyAction,
    PolicyProcessorPipeline,
    RobotAction,
    RobotObservation,
    RobotProcessorPipeline,
    make_default_processors,
)
from dual_arm.processor.rename_processor import rename_stats
from dual_arm.robots import (  # noqa: F401
    Robot,
    RobotConfig,
    bi_openarm_follower,
    bi_so_follower,
    earthrover_mini_plus,
    hope_jr,
    koch_follower,
    make_robot_from_config,
    omx_follower,
    openarm_follower,
    reachy2,
    so_follower,
    unitree_g1 as unitree_g1_robot,
)
from dual_arm.teleoperators import (  # noqa: F401
    Teleoperator,
    TeleoperatorConfig,
    bi_openarm_leader,
    bi_so_leader,
    homunculus,
    koch_leader,
    make_teleoperator_from_config,
    omx_leader,
    openarm_leader,
    reachy2_teleoperator,
    so_leader,
    unitree_g1,
)
from dual_arm.teleoperators.keyboard.teleop_keyboard import KeyboardTeleop
from dual_arm.utils.constants import ACTION, OBS_STR
from dual_arm.utils.control_utils import (
    init_keyboard_listener,
    is_headless,
    predict_action,
    sanity_check_dataset_name,
    sanity_check_dataset_robot_compatibility,
)
from dual_arm.utils.import_utils import register_third_party_plugins
from dual_arm.utils.robot_utils import precise_sleep
from dual_arm.utils.utils import (
    get_safe_torch_device,
    init_logging,
    log_say,
)
from dual_arm.utils.visualization_utils import init_rerun, log_rerun_data
from dual_arm.scripts.calibrate_origin_keyboard import calibrate_origin
from dual_arm.scripts.return_to_origin import return_to_origin

from dual_arm.scripts.command_control import (
    CommandState,
    ObjectColor,
    POLICY_REGISTRY,
    RobotMode,
    get_policy_path_for_color,
    get_chunk_size_for_color,
    set_command_idle,
    snapshot_command,
    start_command_server,
)

HOME_TOLERANCE = int(os.getenv("HOME_TOLERANCE", "100"))
FAST_SYNC_DURATION = float(os.getenv("FAST_SYNC_DURATION", "1.5"))
FAST_SYNC_FPS = int(os.getenv("FAST_SYNC_FPS", "20"))
FAST_SYNC_SETTLE_TIME = float(os.getenv("FAST_SYNC_SETTLE_TIME", "1.5"))
SKIP_HOME_SYNC = os.getenv("SKIP_HOME_SYNC", "0") == "1"
ENABLE_COMMAND_CONTROL = os.getenv("ENABLE_COMMAND_CONTROL", "1") == "1"

FOLLOWER_TARGET_POSITIONS = {
     "shoulder_pan": 2388, "shoulder_lift": 2048, "elbow_pitch": 2048,
    "elbow_roll": 2048, "wrist_yaw": 2048, "wrist_roll": 2048, "wrist_pitch": 2958, "gripper": 2048,
}

LEADER_TARGET_POSITIONS = {
     "shoulder_pan": 2728, "shoulder_lift": 2048, "elbow_pitch": 2048,
    "elbow_roll": 2958, "wrist_yaw": 2048, "wrist_roll": 2048, "wrist_pitch": 2958, "gripper": 2048,
}


@dataclass
class DatasetRecordConfig:
    repo_id: str
    single_task: str
    root: str | Path | None = None
    fps: int = 15
    episode_time_s: int | float = 60
    reset_time_s: int | float = 60
    num_episodes: int = 50
    video: bool = True
    push_to_hub: bool = True
    private: bool = False
    tags: list[str] | None = None
    num_image_writer_processes: int = 0
    num_image_writer_threads_per_camera: int = 4
    video_encoding_batch_size: int = 1
    vcodec: str = "libsvtav1"
    rename_map: dict[str, str] = field(default_factory=dict)

    def __post_init__(self):
        if self.single_task is None:
            raise ValueError("You need to provide a task as argument in `single_task`.")
        if self.fps <= 0:
            raise ValueError(f"fps must be greater than 0, got {self.fps}")


@dataclass
class RecordConfig:
    robot: RobotConfig
    dataset: DatasetRecordConfig
    teleop: TeleoperatorConfig | None = None
    policy: PreTrainedConfig | None = None
    display_data: bool = False
    display_ip: str | None = None
    display_port: int | None = None
    display_compressed_images: bool = False
    play_sounds: bool = True
    resume: bool = False

    def __post_init__(self):
        policy_path = parser.get_path_arg("policy")
        if policy_path:
            cli_overrides = parser.get_cli_overrides("policy")
            self.policy = PreTrainedConfig.from_pretrained(policy_path, cli_overrides=cli_overrides)
            self.policy.pretrained_path = policy_path
        if self.teleop is None and self.policy is None:
            raise ValueError("Choose a policy, a teleoperator or both to control the robot")

    @classmethod
    def __get_path_fields__(cls) -> list[str]:
        return ["policy"]


def handle_overflow(val: int | float) -> int | float:
    """XL430 32-bit signed integer overflow 보정."""
    if val > 2147483647:
        return val - 4294967296
    return val

"""
초기 위치 이동 관련 함수 
is_near_target
torque_off_if_possible
move_bus_to_target
assert_near_home_after_sync
fast_sync_to_target
reset_follower_before_exit
"""
def is_near_target(
    raw_dict: dict,
    motors,
    target_positions: dict,
    tolerance: int = HOME_TOLERANCE,
) -> bool:
    """모든 모터가 목표 위치 근처면 True."""
    for motor in motors:
        current = raw_dict.get(motor, 2048)
        target = target_positions.get(motor, 2048)

        if abs(current - target) > tolerance:
            logging.warning(
                f"[Sync] {motor} target check failed: "
                f"current={current}, target={target}, diff={abs(current - target)}, tolerance={tolerance}"
            )
            return False

    return True

def torque_off_if_possible(teleop: Teleoperator | None):
    """리더 토크를 가능한 한 빨리 꺼서 바로 조종 가능하게 함."""
    if teleop and hasattr(teleop, "bus"):
        try:
            teleop.bus.disable_torque()
        except Exception as exc:
            logging.warning(f"Failed to disable teleop torque: {exc}")


def move_bus_to_target(
    bus,
    target_positions: dict,
    name: str,
    duration: float = FAST_SYNC_DURATION,
    fps: int = FAST_SYNC_FPS,
):
    """
    하나의 bus(follower 또는 leader)를 목표 초기 위치로 순차 이동.
    """
    raw = bus.sync_read("Present_Position", normalize=False)
    raw = {k: handle_overflow(v) for k, v in raw.items()}

    print(f"[Sync] {name} 초기 위치 이동 시작")

    steps = max(1, int(fps * duration))
    sleep_dt = 1.0 / max(1, fps)

    for i in range(steps):
        alpha = (i + 1) / steps
        goal = {}

        for motor in bus.motors:
            start_val = raw.get(motor, 2048)
            target_val = target_positions.get(motor, 2048)
            goal_val = int(start_val + (target_val - start_val) * alpha)
            goal[motor] = goal_val

        bus.sync_write("Goal_Position", goal, normalize=False)
        time.sleep(sleep_dt)

    print(f"[Sync] {name} 초기 위치 이동 명령 완료")


def assert_near_home_after_sync(
    robot: Robot,
    teleop: Teleoperator | None,
    follower_targets: dict = FOLLOWER_TARGET_POSITIONS,
    leader_targets: dict = LEADER_TARGET_POSITIONS,
    tolerance: int = HOME_TOLERANCE,
):
    """
    초기 위치 이동 후 실제 현재 위치가 목표 근처인지 확인.
    확인 실패 시 record_loop에 들어가지 않고 RuntimeError 발생.
    """
    robot_raw = robot.bus.sync_read("Present_Position", normalize=False)
    robot_raw = {k: handle_overflow(v) for k, v in robot_raw.items()}

    robot_ok = is_near_target(
        robot_raw,
        robot.bus.motors,
        follower_targets,
        tolerance=tolerance,
    )

    teleop_ok = True
    teleop_raw = {}

    if teleop and hasattr(teleop, "bus"):
        teleop_raw = teleop.bus.sync_read("Present_Position", normalize=False)
        teleop_raw = {k: handle_overflow(v) for k, v in teleop_raw.items()}

        teleop_ok = is_near_target(
            teleop_raw,
            teleop.bus.motors,
            leader_targets,
            tolerance=tolerance,
        )

    logging.info(f"[Sync] follower raw after sync: {robot_raw}")
    logging.info(f"[Sync] leader raw after sync: {teleop_raw}")

    if not robot_ok or not teleop_ok:
        raise RuntimeError(
            "[Sync] 초기 위치 확인 실패\n"
            f"robot_ok={robot_ok}, teleop_ok={teleop_ok}\n"
            f"robot_raw={robot_raw}\n"
            f"teleop_raw={teleop_raw}\n"
            f"follower_targets={follower_targets}\n"
            f"leader_targets={leader_targets}\n"
            f"tolerance={tolerance}"
        )

    print("[Sync] follower/leader 초기 위치 확인 완료")


def fast_sync_to_target(
    robot: Robot,
    teleop: Teleoperator | None,
    follower_targets: dict = FOLLOWER_TARGET_POSITIONS,
    leader_targets: dict = LEADER_TARGET_POSITIONS,
    duration: float = FAST_SYNC_DURATION,
    fps: int = FAST_SYNC_FPS,
    settle_time: float = FAST_SYNC_SETTLE_TIME,
    tolerance: int = HOME_TOLERANCE,
):
    """
    시작 시 follower(robot)와 leader(teleop)를 목표 위치로 순차 이동.
    1. follower 초기 위치 이동 
    2. follower 이동 완료 출력
    3. leader 초기 위치 이동
    4. leader 이동 완료 출력
    5. 실제 위치 검증 후 record_loop 진입
    """
    if SKIP_HOME_SYNC:
        print("[Sync] SKIP_HOME_SYNC=1: 초기 위치 이동 및 확인 생략")
        torque_off_if_possible(teleop)
        return

    if not hasattr(robot, "bus"):
        print("[Sync] robot.bus가 없어 초기 위치 이동 생략")
        torque_off_if_possible(teleop)
        return

    robot.bus.enable_torque()

    if teleop and hasattr(teleop, "bus"):
        teleop.bus.enable_torque()

    robot_raw = robot.bus.sync_read("Present_Position", normalize=False)
    robot_raw = {k: handle_overflow(v) for k, v in robot_raw.items()}

    teleop_raw = {}
    if teleop and hasattr(teleop, "bus"):
        teleop_raw = teleop.bus.sync_read("Present_Position", normalize=False)
        teleop_raw = {k: handle_overflow(v) for k, v in teleop_raw.items()}

    robot_near_target = is_near_target(
        robot_raw,
        robot.bus.motors,
        follower_targets,
        tolerance=tolerance,
    )

    teleop_near_target = True
    if teleop and hasattr(teleop, "bus"):
        teleop_near_target = is_near_target(
            teleop_raw,
            teleop.bus.motors,
            leader_targets,
            tolerance=tolerance,
        )

    if robot_near_target and teleop_near_target:
        print(f"[Sync] 이미 목표 위치 근처입니다. 이동 생략. tolerance={tolerance}")

        assert_near_home_after_sync(
            robot=robot,
            teleop=teleop,
            follower_targets=follower_targets,
            leader_targets=leader_targets,
            tolerance=tolerance,
        )

        torque_off_if_possible(teleop)
        logging.info("Leader torque OFF after already-near check.")
        return

    print(f"[Sync] 초기 목표 위치 순차 이동 시작: duration={duration}s, fps={fps}")

    if not robot_near_target:
        move_bus_to_target(
            bus=robot.bus,
            target_positions=follower_targets,
            name="follower",
            duration=duration,
            fps=fps,
        )

        if settle_time > 0:
            time.sleep(settle_time)

        print("[Sync] follower 초기 위치 이동 완료")
    else:
        print("[Sync] follower는 이미 목표 위치 근처입니다. 이동 생략")

    if teleop and hasattr(teleop, "bus"):
        if not teleop_near_target:
            move_bus_to_target(
                bus=teleop.bus,
                target_positions=leader_targets,
                name="leader teleop",
                duration=duration,
                fps=fps,
            )

            if settle_time > 0:
                time.sleep(settle_time)

            print("[Sync] leader teleop 초기 위치 이동 완료")
        else:
            print("[Sync] leader teleop은 이미 목표 위치 근처입니다. 이동 생략")
    else:
        print("[Sync] leader teleop bus가 없어 leader 초기 위치 이동 생략")

    if settle_time > 0:
        time.sleep(settle_time)

    assert_near_home_after_sync(
        robot=robot,
        teleop=teleop,
        follower_targets=follower_targets,
        leader_targets=leader_targets,
        tolerance=tolerance,
    )

    torque_off_if_possible(teleop)
    logging.info("Leader torque OFF after sync check.")

    print("[Sync] follower/leader 순차 초기 위치 이동 완료. 데이터 취득 시작 가능.")

def reset_follower_before_exit(
    robot: Robot,
    follower_targets: dict = FOLLOWER_TARGET_POSITIONS,
    tolerance: int = 60,
    duration: float = 1.5,
    fps: int = 20,
    settle_time: float = 0.5,
):
    """프로그램 종료 전에 follower를 초기 위치로 이동."""
    if robot is None or not getattr(robot, "is_connected", False):
        logging.warning("[Exit Sync] robot is not connected. reset skipped.")
        return False

    if not hasattr(robot, "bus"):
        logging.warning("[Exit Sync] robot.bus not found. reset skipped.")
        return False

    try:
        robot.bus.enable_torque()
    except Exception as exc:
        logging.warning(f"[Exit Sync] torque enable failed: {exc}")

    robot_raw = robot.bus.sync_read("Present_Position", normalize=False)
    robot_raw = {k: handle_overflow(v) for k, v in robot_raw.items()}

    robot_ok = is_near_target(
        robot_raw,
        robot.bus.motors,
        follower_targets,
        tolerance=tolerance,
    )

    if robot_ok:
        logging.info("[Exit Sync] follower already near target.")
        return True

    logging.info("[Exit Sync] follower 초기 위치 복귀 시작")

    move_bus_to_target(
        bus=robot.bus,
        target_positions=follower_targets,
        name="follower exit reset",
        duration=duration,
        fps=fps,
    )

    if settle_time > 0:
        time.sleep(settle_time)

    robot_raw = robot.bus.sync_read("Present_Position", normalize=False)
    robot_raw = {k: handle_overflow(v) for k, v in robot_raw.items()}

    robot_ok = is_near_target(
        robot_raw,
        robot.bus.motors,
        follower_targets,
        tolerance=tolerance,
    )

    logging.info(f"[Exit Sync] follower reset result={robot_ok}, raw={robot_raw}")
    return robot_ok

@dataclass
class PolicyRuntime:
    path: str
    policy: PreTrainedPolicy
    preprocessor: PolicyProcessorPipeline
    postprocessor: PolicyProcessorPipeline

def make_policy_runtime(
    policy_path: str,
    dataset: LeRobotDataset,
    rename_map: dict[str, str],
    chunk_size: int | None = None,
) -> PolicyRuntime:
    path = str(policy_path)
    if not Path(path).exists():
        raise FileNotFoundError(f"Policy path does not exist: {path}")

    cli_overrides = parser.get_cli_overrides("policy")
    
    # 리스트 형태인 경우 딕셔너리로 변환 (draccus 오버라이드 호환성)
    if isinstance(cli_overrides, list):
        new_overrides = {}
        for item in cli_overrides:
            if "=" in item:
                k, v = item.split("=", 1)
                new_overrides[k.lstrip("-")] = v
        cli_overrides = new_overrides
    elif cli_overrides is None:
        cli_overrides = {}

    # chunk_size 오버라이드 적용
    if chunk_size is not None:
        logging.info(f"[Command] Overriding chunk_size to {chunk_size} via cli_overrides for {path}")
        cli_overrides["chunk_size"] = chunk_size
        cli_overrides["n_action_steps"] = chunk_size

    policy_cfg = PreTrainedConfig.from_pretrained(path, cli_overrides=cli_overrides)
    policy_cfg.pretrained_path = path

    policy = make_policy(policy_cfg, ds_meta=dataset.meta)
    preprocessor, postprocessor = make_pre_post_processors(
        policy_cfg=policy_cfg,
        pretrained_path=policy_cfg.pretrained_path,
        dataset_stats=rename_stats(dataset.meta.stats, rename_map),
        preprocessor_overrides={
            "device_processor": {"device": policy_cfg.device},
            "rename_observations_processor": {"rename_map": rename_map},
        },
    )

    return PolicyRuntime(
        path=path,
        policy=policy,
        preprocessor=preprocessor,
        postprocessor=postprocessor,
    )


def get_or_load_policy_runtime(
    policy_path: str,
    policy_runtime_cache: dict[str, PolicyRuntime],
    dataset: LeRobotDataset,
    rename_map: dict[str, str],
    chunk_size: int | None = None,
) -> PolicyRuntime:
    path = str(policy_path)
    if path not in policy_runtime_cache:
        logging.info("[Command] Loading full policy: %s (chunk_size=%s)", path, chunk_size)
        policy_runtime_cache[path] = make_policy_runtime(path, dataset, rename_map, chunk_size=chunk_size)

    return policy_runtime_cache[path]



@safe_stop_image_writer
def record_loop(
    robot: Robot,
    events: dict,
    fps: int,
    teleop_action_processor: RobotProcessorPipeline,
    robot_action_processor: RobotProcessorPipeline,
    robot_observation_processor: RobotProcessorPipeline,
    dataset: LeRobotDataset | None = None,
    teleop: Teleoperator | list[Teleoperator] | None = None,
    policy: PreTrainedPolicy | None = None,
    preprocessor: PolicyProcessorPipeline | None = None,
    postprocessor: PolicyProcessorPipeline | None = None,
    control_time_s: int | None = None,
    single_task: str | None = None,
    display_data: bool = False,
    display_compressed_images: bool = False,
    command_state: Optional[CommandState] = None,
    command_state_lock=None,
    policy_runtime_cache: dict[str, PolicyRuntime] | None = None,
    dataset_rename_map: dict[str, str] | None = None,
):
    if dataset is not None and dataset.fps != fps:
        raise ValueError(f"The dataset fps should be equal to requested fps ({dataset.fps} != {fps}).")

    teleop_arm = teleop_keyboard = None
    if isinstance(teleop, list):
        teleop_keyboard = next((t for t in teleop if isinstance(t, KeyboardTeleop)), None)
        teleop_arm = next(
            (
                t
                for t in teleop
                if isinstance(
                    t,
                    (
                        so_leader.SO100Leader
                        | so_leader.SO101Leader
                        | koch_leader.KochLeader
                        | omx_leader.OmxLeader
                    ),
                )
            ),
            None,
        )

    if policy is not None and preprocessor is not None and postprocessor is not None:
        policy.reset()
        preprocessor.reset()
        postprocessor.reset()

    timestamp = 0
    loop_count = 0
    start_episode_t = None  # 초기 지연 제외를 위해 None으로 시작

    recent_fps_window = deque(maxlen=10)
    recent_avg_fps = float(fps)
    # =========================================================
    # 수정한 부분:
    # 목표 FPS와 현재 루프의 순간 FPS 차이가 1 이상이면
    # "다음 루프"에서 policy 추론 대신 이전 action을 재사0용한다.
    #
    # 예) 목표 fps=15 일 때
    # - current_fps = 14.2 -> 차이 0.8 -> 재사용 안 함
    # - current_fps = 14.0 -> 차이 1.0 -> 재사용 함
    # - current_fps = 13.5 -> 차이 1.5 -> 재사용 함
    # =========================================================
    target_dt = 1.0 / fps
    current_fps = float(fps)
    fps_reuse_threshold = 1.0
    prev_loop_fps_gap_large = False

    # 이전 action 재사용 관련 상태 변수
    last_action_values = None
    reused_action_count = 0
    consecutive_reuse_count = 0
    max_consecutive_reuse = 3  # 너무 오래 같은 action만 쓰지 않도록 제한

    active_policy_path = None
    if policy is not None and getattr(policy.config, "pretrained_path", None):
        active_policy_path = str(policy.config.pretrained_path)
    last_idle_log_t = 0.0
    last_command_version = -1
    last_mode = RobotMode.IDLE
    last_target_color = ObjectColor.NONE

    # [수정] 루프 진입 시 정책(POLICY) 명령이 이미 있다면 즉시 실행할 수 있도록 last_command_version을 설정
    if ENABLE_COMMAND_CONTROL:
        m, _, v = snapshot_command(command_state, command_state_lock)
        # POLICY 모드라면 바로 인식하도록 v-1 설정, 그 외(RESET/IDLE)는 현재 버전으로 동기화하여 중복 실행 방지
        last_command_version = v - 1 if m == RobotMode.POLICY else v

    with ThreadPoolExecutor(max_workers=2) as executor:
        while timestamp < control_time_s:
            start_loop_t = time.perf_counter()
            if events["exit_early"] or events["stop_recording"]:
                events["exit_early"] = False
                break

            mode, target_color, command_version = snapshot_command(command_state, command_state_lock)

            if command_version > last_command_version:
                print(f"\n[Command] 명령 수신: 모드={mode.value}, 타겟={target_color.value} (v{command_version})")

                # POLICY 모드로 새로 진입하거나 타겟 색상이 바뀌면 정책 상태 리셋
                if mode == RobotMode.POLICY:
                    # 로봇에 현재 타겟 색상을 동적으로 전달 (그리퍼 범위 제어용)
                    if hasattr(robot, "current_target_color"):
                        robot.current_target_color = target_color.value

                    if last_mode != RobotMode.POLICY or target_color != last_target_color:

                        if policy is not None:
                            logging.info("[Command] New policy task start. Resetting policy state.")
                            policy.reset()
                            if preprocessor: preprocessor.reset()
                            if postprocessor: postprocessor.reset()
                            last_action_values = None
                            consecutive_reuse_count = 0

                last_command_version = command_version
                last_mode = mode
                last_target_color = target_color

            if mode == RobotMode.EXIT:
                logging.info("[Command] Exit requested.")
                events["stop_recording"] = True
                break

            if mode == RobotMode.RESET_HOME:
                logging.info("[Command] Reset-home requested. Restarting episode.")

                # 명령 기반 초기화: follower를 홈 위치로 이동
                reset_follower_before_exit(
                    robot=robot,
                    follower_targets=FOLLOWER_TARGET_POSITIONS,
                    tolerance=60,
                    duration=1.5,
                    fps=20,
                    settle_time=0.5,
                )

                # 초기화 이후 이전 policy/action 상태가 남아 있으면
                # 다음 명령에서 멈춘 것처럼 보이거나 이전 action이 재사용될 수 있으므로 모두 리셋
                if policy is not None:
                    policy.reset()
                if preprocessor is not None:
                    preprocessor.reset()
                if postprocessor is not None:
                    postprocessor.reset()

                last_action_values = None
                consecutive_reuse_count = 0
                prev_loop_fps_gap_large = False

                # command state를 idle로 돌리고 현재 episode buffer를 버리도록 표시
                set_command_idle(command_state, command_state_lock)
                events["rerecord_episode"] = True
                break

            if mode == RobotMode.IDLE and policy is not None:
                now = time.perf_counter()
                if now - last_idle_log_t >= 1.0:
                    logging.info("[Command] Idle mode. Waiting for a policy command.")
                    last_idle_log_t = now
                precise_sleep(max(target_dt - (time.perf_counter() - start_loop_t), 0))
                continue

            # 실제 동작 시작 시점에 시간 기록 (초기 지연 제외)
            if start_episode_t is None:
                start_episode_t = time.perf_counter()

            if mode == RobotMode.POLICY:
                # [개선] 데이터셋이 없어도 추론은 가능해야 하므로 조건 분리
                target_policy_path = get_policy_path_for_color(target_color)
                target_chunk_size = get_chunk_size_for_color(target_color)
                
                # 만약 command_control에 설정된 경로가 없으면, 현재 실행 시 로드된 기본 정책 경로 사용
                if not target_policy_path and active_policy_path:
                    target_policy_path = active_policy_path
                
                if target_policy_path:
                    if policy_runtime_cache is None:
                        policy_runtime_cache = {}
                    
                    if active_policy_path != target_policy_path:
                        logging.info(f"[Command] 정책 교체 시도: {target_policy_path} (chunk_size={target_chunk_size})")
                        try:
                            runtime = get_or_load_policy_runtime(
                                policy_path=target_policy_path,
                                policy_runtime_cache=policy_runtime_cache,
                                dataset=dataset,
                                rename_map=dataset_rename_map or {},
                                chunk_size=target_chunk_size,
                            )

                            logging.info(f"[Command] 정책 로드 완료: {runtime.path}")
                            policy = runtime.policy
                            preprocessor = runtime.preprocessor
                            postprocessor = runtime.postprocessor
                            policy.reset()
                            preprocessor.reset()
                            postprocessor.reset()
                            last_action_values = None
                            consecutive_reuse_count = 0
                            active_policy_path = runtime.path
                        except Exception as e:
                            logging.error(f"[Command] 정책 로드 실패: {e}")
                else:
                    logging.warning(f"[Command] 타겟({target_color.value})에 해당하는 정책 경로를 찾을 수 없습니다.")

            # 1. observation / teleop action 읽기
            if policy is None and isinstance(teleop, Teleoperator):
                future_obs = executor.submit(robot.get_observation)
                future_act = executor.submit(teleop.get_action)
                obs = future_obs.result()
                act = future_act.result()

                # # 사용자가 추가했던 그리퍼 보정 유지
                # if act is not None and "gripper.pos" in act:
                #     act["gripper.pos"] += 10
                #     act["gripper.pos"] *= 1.5
            else:
                obs = robot.get_observation()
                act = None

                # # 팔로워 보정
                # obs = {
                #     k: handle_overflow(v) if isinstance(v, (int, float)) else v
                #     for k, v in obs.items()
                # }

                if policy is None and isinstance(teleop, list):
                    arm_action = teleop_arm.get_action()
                    arm_action = {f"arm_{k}": v for k, v in arm_action.items()}

                    keyboard_action = teleop_keyboard.get_action()
                    base_action = robot._from_keyboard_to_base_action(keyboard_action)

                    act = {**arm_action, **base_action} if len(base_action) > 0 else arm_action

            obs_processed = robot_observation_processor(obs)

            if policy is not None or dataset is not None:
                observation_frame = build_dataset_frame(dataset.features, obs_processed, prefix=OBS_STR)

            # 2. action 결정
            if policy is not None and preprocessor is not None and postprocessor is not None:
                # =========================================================
                # 수정한 부분:
                # 직전 루프에서 목표 FPS와 현재 FPS 차이가 1 이상이었고,
                # 이전 action이 존재하면 이번 루프에서는 추론을 생략하고
                # 이전 action을 재사용한다.
                # =========================================================
                should_reuse_action = (
                    prev_loop_fps_gap_large
                    and last_action_values is not None
                    and consecutive_reuse_count < max_consecutive_reuse
                )

                if should_reuse_action:
                    action_values = last_action_values
                    reused_action_count += 1
                    consecutive_reuse_count += 1

                    if reused_action_count % 30 == 0:
                        logging.warning(
                            f"Policy inference skipped {reused_action_count} times "
                            f"because FPS gap >= {fps_reuse_threshold:.1f}"
                        )
                else:
                    action_values = predict_action(
                        observation=observation_frame,
                        policy=policy,
                        device=get_safe_torch_device(policy.config.device),
                        preprocessor=preprocessor,
                        postprocessor=postprocessor,
                        use_amp=policy.config.use_amp,
                        task=single_task,
                        robot_type=robot.robot_type,
                    )
                    action_values = make_robot_action(action_values, dataset.features)

                    # 새로 추론한 action 저장
                    last_action_values = action_values
                    consecutive_reuse_count = 0

            elif act is not None:
                action_values = teleop_action_processor((act, obs))
            
            else:
                # precise_sleep으로 루프 주기 맞춤
                dt_s = time.perf_counter() - start_loop_t
                precise_sleep(max(target_dt - dt_s, 0))
                continue
            
            # # 리더 액션 보정
            # action_values = {
            # k: handle_overflow(v) if isinstance(v, (int, float)) else v
            # for k, v in action_values.items()
            # }

            # 3. follower로 action 전송
            robot_action_to_send = robot_action_processor((action_values, obs))
            robot.send_action(robot_action_to_send)

            # 4. dataset 저장
            if dataset is not None:
                action_frame = build_dataset_frame(dataset.features, action_values, prefix=ACTION)
                frame = {**observation_frame, **action_frame, "task": single_task}
                dataset.add_frame(frame)

            if display_data:
                log_rerun_data(
                    observation=obs_processed,
                    action=action_values,
                    compress_images=display_compressed_images,
                )

            loop_count += 1
            dt_s = time.perf_counter() - start_loop_t

            # =========================================================
            # 수정한 부분:
            # 루프가 끝난 뒤 순간 FPS 계산
            # 이 값을 가지고 "다음 루프"에서 재사용할지 결정한다.
            # =========================================================
            current_fps = 1.0 / dt_s if dt_s > 0 else float(fps)
                        
                        # print용 최근 10프레임 평균 FPS
            recent_fps_window.append(current_fps)
            recent_avg_fps = sum(recent_fps_window) / len(recent_fps_window)
            
            fps_gap = fps - current_fps
            prev_loop_fps_gap_large = fps_gap >= fps_reuse_threshold

            if loop_count % fps == 0 and start_episode_t is not None:
                avg_fps = loop_count / (time.perf_counter() - start_episode_t)
                print(
                    f"[실시간 정보] 모드: {mode.value} | 타겟: {target_color.value} | 목표 FPS: {fps} | 실제 평균 FPS: {avg_fps:.2f} "
                    f"| 최근 평균 FPS(10프레임): {recent_avg_fps:.2f} "
                )

            if prev_loop_fps_gap_large and loop_count % 30 == 0:
                logging.warning(
                    f"FPS dropped below threshold: current_fps={current_fps:.2f}, target_fps={fps}"
                )

            precise_sleep(max(target_dt - dt_s, 0))
            timestamp = loop_count / fps


@parser.wrap()
def record(cfg: RecordConfig) -> LeRobotDataset:
    init_logging()
    logging.info(pformat(asdict(cfg)))

    if cfg.display_data:
        init_rerun(session_name="recording", ip=cfg.display_ip, port=cfg.display_port)

    display_compressed_images = (
        True
        if (cfg.display_data and cfg.display_ip is not None and cfg.display_port is not None)
        else cfg.display_compressed_images
    )

    robot = make_robot_from_config(cfg.robot)
    teleop = make_teleoperator_from_config(cfg.teleop) if cfg.teleop is not None else None



    teleop_action_processor, robot_action_processor, robot_observation_processor = make_default_processors()

    dataset_features = combine_feature_dicts(
        aggregate_pipeline_dataset_features(
            pipeline=teleop_action_processor,
            initial_features=create_initial_features(action=robot.action_features),
            use_videos=cfg.dataset.video,
        ),
        aggregate_pipeline_dataset_features(
            pipeline=robot_observation_processor,
            initial_features=create_initial_features(observation=robot.observation_features),
            use_videos=cfg.dataset.video,
        ),
    )

    dataset = None
    listener = None

    try:
        if cfg.resume:
            dataset = LeRobotDataset(
                cfg.dataset.repo_id,
                root=cfg.dataset.root,
                batch_encoding_size=cfg.dataset.video_encoding_batch_size,
                vcodec=cfg.dataset.vcodec,
            )

            if hasattr(robot, "cameras") and len(robot.cameras) > 0:
                dataset.start_image_writer(
                    num_processes=cfg.dataset.num_image_writer_processes,
                    num_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
                )

            sanity_check_dataset_robot_compatibility(
                dataset,
                robot,
                cfg.dataset.fps,
                dataset_features,
            )
        else:
            sanity_check_dataset_name(cfg.dataset.repo_id, cfg.policy)
            dataset = LeRobotDataset.create(
                cfg.dataset.repo_id,
                cfg.dataset.fps,
                root=cfg.dataset.root,
                robot_type=robot.name,
                features=dataset_features,
                use_videos=cfg.dataset.video,
                image_writer_processes=cfg.dataset.num_image_writer_processes,
                image_writer_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
                batch_encoding_size=cfg.dataset.video_encoding_batch_size,
                vcodec=cfg.dataset.vcodec,
            )

        policy = None if cfg.policy is None else make_policy(cfg.policy, ds_meta=dataset.meta)
        preprocessor = postprocessor = None
        policy_runtime_cache: dict[str, PolicyRuntime] = {}

        if cfg.policy is not None:
            # 초기 로드되는 정책의 색상을 판별하여 chunk_size 적용
            initial_color = ObjectColor.NONE
            for color, path in POLICY_REGISTRY.items():
                if str(cfg.policy.pretrained_path) == str(path):
                    initial_color = color
                    break
            
            initial_chunk_size = get_chunk_size_for_color(initial_color)
            if initial_chunk_size is not None:
                logging.info(f"[Init] Overriding initial policy chunk_size to {initial_chunk_size}")
                cfg.policy.chunk_size = initial_chunk_size
                if hasattr(cfg.policy, "n_action_steps") and getattr(cfg.policy, "temporal_ensemble_coeff", None) is None:
                    cfg.policy.n_action_steps = initial_chunk_size

            preprocessor, postprocessor = make_pre_post_processors(
                policy_cfg=cfg.policy,
                pretrained_path=cfg.policy.pretrained_path,
                dataset_stats=rename_stats(dataset.meta.stats, cfg.dataset.rename_map),
                preprocessor_overrides={
                    "device_processor": {"device": cfg.policy.device},
                    "rename_observations_processor": {"rename_map": cfg.dataset.rename_map},
                },
            )
            if policy is not None and preprocessor is not None and postprocessor is not None:
                # 초기 정책을 캐시에 넣을 때도 적용된 설정 유지
                policy_runtime_cache[str(cfg.policy.pretrained_path)] = PolicyRuntime(
                    path=str(cfg.policy.pretrained_path),
                    policy=policy,
                    preprocessor=preprocessor,
                    postprocessor=postprocessor,
                )
        
        robot.connect()
        if teleop is not None:
            teleop.connect()
        
        fast_sync_to_target(robot, teleop)
        time.sleep(2.0)

        listener, events = init_keyboard_listener()
        command_state = CommandState()
        command_state_lock = Lock()
        command_server_thread = None
        if ENABLE_COMMAND_CONTROL:
            command_server_thread = start_command_server(command_state, command_state_lock, events, host="127.0.0.1", port=8765) 

        print(
            "\n"
            + "=" * 60
            + "\n [안내] 다른 터미널에서 command_control.py를 실행해 명령을 입력하세요.\n"
            + "       예시: 초록 물체 잡아줘 / 빨간 물체 잡아줘 / 파란 물체 잡아줘 / 멈춰 / 초기화 / 종료\n"
            + "=" * 60
            + "\n"
        )
        try:
            with VideoEncodingManager(dataset):
                recorded_episodes = 0

                while recorded_episodes < cfg.dataset.num_episodes and not events["stop_recording"]:
                    if sys.stdin in select.select([sys.stdin], [], [], 0)[0]:
                        line = sys.stdin.readline().strip().lower()
                        if line == "q":
                            events["stop_recording"] = True
                            break

                    log_say(f"Recording episode {recorded_episodes}", cfg.play_sounds)

                    record_loop(
                        robot=robot,
                        events=events,
                        fps=cfg.dataset.fps,
                        teleop_action_processor=teleop_action_processor,
                        robot_action_processor=robot_action_processor,
                        robot_observation_processor=robot_observation_processor,
                        teleop=teleop,
                        policy=policy,
                        preprocessor=preprocessor,
                        postprocessor=postprocessor,
                        dataset=dataset,
                        control_time_s=cfg.dataset.episode_time_s,
                        single_task=cfg.dataset.single_task,
                        display_data=cfg.display_data,
                        display_compressed_images=display_compressed_images,

                        # 추가해야 하는 부분
                        command_state=command_state if ENABLE_COMMAND_CONTROL else None,
                        command_state_lock=command_state_lock if ENABLE_COMMAND_CONTROL else None,
                        policy_runtime_cache=policy_runtime_cache,
                        dataset_rename_map=cfg.dataset.rename_map,
                        )
                    if not events["stop_recording"] and recorded_episodes < cfg.dataset.num_episodes - 1:
                        if events["rerecord_episode"]:
                            # command_control.py의 "초기화" 명령으로 이미 reset_follower_before_exit()를 수행했다.
                            # 여기서 reset_time_s 동안 reset용 record_loop를 다시 실행하면,
                            # policy/dataset이 없는 루프에서 새 명령을 받아 진행이 안 되는 것처럼 보일 수 있다.
                            # 따라서 명령 기반 초기화에서는 reset 대기 루프를 생략하고 바로 다음 episode로 넘어간다.
                            logging.info("[Command] Reset-home completed. Skip reset waiting loop.")
                        else:
                            log_say("Reset the environment", cfg.play_sounds)

                            if robot.name == "unitree_g1":
                                robot.reset()

                            record_loop(
                                robot=robot,
                                events=events,
                                fps=cfg.dataset.fps,
                                teleop_action_processor=teleop_action_processor,
                                robot_action_processor=robot_action_processor,
                                robot_observation_processor=robot_observation_processor,
                                teleop=teleop,
                                control_time_s=cfg.dataset.reset_time_s,
                                single_task=cfg.dataset.single_task,
                                display_data=cfg.display_data,
                                display_compressed_images=display_compressed_images,
                                command_state=command_state if ENABLE_COMMAND_CONTROL else None,
                                command_state_lock=command_state_lock if ENABLE_COMMAND_CONTROL else None,
                                policy_runtime_cache=policy_runtime_cache,
                                dataset_rename_map=cfg.dataset.rename_map,
                            )

                    if events["rerecord_episode"]:
                        events["rerecord_episode"] = False
                        events["exit_early"] = False
                        dataset.clear_episode_buffer()
                        continue

                    dataset.save_episode()
                    recorded_episodes += 1
        finally:
            if listener:
                listener.stop()

    finally:
        log_say("Stop recording", cfg.play_sounds, blocking=True)

        if dataset:
            if hasattr(dataset, "image_writer") and dataset.image_writer:
                safe_stop_image_writer(dataset.image_writer)
            dataset.finalize()

            try:
                reset_follower_before_exit(
                    robot=robot,
                    follower_targets=FOLLOWER_TARGET_POSITIONS,
                    tolerance=60,
                    duration=1.5,
                    fps=20,
                    settle_time=0.5,
                )
                robot.bus.enable_torque()
            
            except Exception as exc:
                logging.exception(f"[Exit Sync] reset_follower_before_exit failed: {exc}")

        if robot.is_connected:
            robot.disconnect()

        if teleop and teleop.is_connected:
            teleop.disconnect()

        if not is_headless() and listener:
            listener.stop()

        if cfg.dataset.push_to_hub:
            dataset.push_to_hub(tags=cfg.dataset.tags, private=cfg.dataset.private)

        log_say("Exiting", cfg.play_sounds)

    return dataset


def main():
    calibrate_origin()
    time.sleep(0.5)
    register_third_party_plugins()
    record()


if __name__ == "__main__":
    main()